---
- name: "Update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "Upgrade packages"
  become: yes
  apt:
    upgrade: "yes"

- name: "Remove dependencies that are no longer required"
  become: yes
  apt:
    autoremove: yes

- name: "Install nodejs"
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "Install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "Start pm2"
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm --name backend -- start
