---
- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: ~/project/artifact.tar.gz
    dest: ~/backend/

- name: Uncompress Backend
  shell: |
    cd ~/backend
    tar xzf artifact.tar.gz -C . && rm -rf artifact.tar.gz

- name: Install Backend
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm i
    npm audit fix --audit-level=critical --force

- name: Build Backend
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm run build

- name: Start pm2 from backend
  shell: |
    cd ~/backend 
    pm2 start npm --name backend -- start
    pm2 ls
