---
- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: ~/project/artifact.tar.gz
    dest: ~/backend/

- name: Uncompress Backend
  shell: |
    cd ~/backend
    tar xzf artifact.tar.gz -C . && rm -rf artifact.tar.gz

- name: Build Backend
  shell: |
    cd /home/ubuntu/backend
    npm i
    npm run build
    # npm audit fix --audit-level=critical --force

- name: Start pm2 from backend
  shell: |
    cd /home/ubuntu/backend
    # pm2 -u ubuntu start npm --name backend -- start
    pm2 start npm --name backend -- start
